In [10]:
import gym
import numpy as np

In [6]:
env=gym.make('FrozenLake-v0')

In [7]:
env.render()


SFFF
FHFH
FFFH
HFFG


 `[(transition probability, next state, reward, Is terminal state?)].`

In [41]:
record=np.zeros([env.observation_space.n])
record.shape

(16,)

In [52]:
record=np.zeros([env.observation_space.n])
threshold=1e-16
for i in range(5000):
    old_record=np.copy(record)
    record=np.zeros(record.shape)
    for state in range(env.observation_space.n):
        Q_values=[]
        for action in range(env.action_space.n):
            next_rewards=0
            for transition in ((env.P[state][action])):
                # print(transition)
                transition_probability, next_state, reward, Is_terminal_state=transition
                # if reward==1:
                #     print('here')
                #     print(transition)
                #     print(state,action)
                next_rewards+=transition_probability*(reward+old_record[next_state])
            
                # record[state]+=transition_probability*reward+np.sum(old_record[next_state])
            
            Q_values.append(next_rewards)
        record[state]=np.max(Q_values)
    if(np.sum(np.abs(record-old_record))<threshold):
        print(i)
        break
    if i%100 == 0:
        print(record)

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.33333333 0.        ]
[0.74612083 0.72042399 0.70220817 0.69276611 0.75177057 0.
 0.47426439 0.         0.76265501 0.77797524 0.72457452 0.
 0.         0.85000899 0.92439446 0.        ]
[0.8168984  0.81467569 0.81309743 0.8122785  0.81738106 0.
 0.52467049 0.         0.81831127 0.8196213  0.76125916 0.
 0.         0.87957793 0.93973656 0.        ]
[0.82296075 0.82277013 0.82263478 0.82256455 0.82300214 0.
 0.52900516 0.         0.82308191 0.82319426 0.7644103  0.
 0.         0.88211496 0.94105299 0.        ]
[0.82348064 0.8234643  0.82345269 0.82344667 0.82348419 0.
 0.5293769  0.         0.82349104 0.82350067 0.76468053 0.
 0.         0.88233253 0.94116588 0.        ]
[0.82352523 0.82352383 0.82352283 0.82352232 0.82352553 0.
 0.52940877 0.         0.82352612 0.82352695 0.76470371 0.
 0.         0.88235119 0.94117556 0.        ]
[0.82352905 0.82

In [53]:
record

array([0.82352941, 0.82352941, 0.82352941, 0.82352941, 0.82352941,
       0.        , 0.52941176, 0.        , 0.82352941, 0.82352941,
       0.76470588, 0.        , 0.        , 0.88235294, 0.94117647,
       0.        ])

In [ ]:
# find path

In [61]:
record

array([0.82352941, 0.82352941, 0.82352941, 0.82352941, 0.82352941,
       0.        , 0.52941176, 0.        , 0.82352941, 0.82352941,
       0.76470588, 0.        , 0.        , 0.88235294, 0.94117647,
       0.        ])

In [70]:
policy=np.zeros(env.observation_space.n)
for state in range(env.observation_space.n):
    temp=[]
    for action in range(env.action_space.n):
        next_rewards=0
        for transition in env.P[state][action]:
            transition_probability, next_state, reward, Is_terminal_state=transition
            next_rewards+=transition_probability*(reward+record[next_state])
        temp.append(next_rewards)
    policy[state]=np.argmax(temp)




In [71]:
policy

array([0., 3., 3., 3., 0., 0., 0., 0., 3., 1., 0., 0., 0., 2., 1., 0.])

## display

### no intuitive

In [74]:
step=0
next_state=0
while(step<50 and next_state!=15):
    step+=1
    state=next_state
    action=policy[state]
    probably=[]
    next_states=[]
    # next_rewards=0
    for transition in env.P[state][action]:
                transition_probability, next_state, reward, Is_terminal_state=transition
                probably.append(transition_probability)
                next_states.append(next_state)
    next_state=np.random.choice(next_states,p=probably)
    print(next_state)

0
4
4
4
4
0
0
0
0
0
0
0
0
0
0
0
0
0
0
4
4
4
8
8
8
9
10
14
15


### intuitive with api `render()`

In [98]:
render=True
for _ in range(1):
    step=0
    state=0
    env.reset()
    while(step<500 and state!=15):
        step+=1
        action=policy[state]
        next_state,reward,done,info=env.step(int(action))
        if done:
            if reward==1:
                print('after {0:} steps, success at {1:}'.format(step,next_state))
            else:
                print('after {0:} steps, failed at {1:}'.format(step,next_state))
            break
        if render:
            env.render()
        state=next_state
    env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFF

In [97]:
render=False
for _ in range(10):
    step=0
    state=0
    env.reset()
    while(step<500 and state!=15):
        step+=1
        action=policy[state]
        next_state,reward,done,info=env.step(int(action))
        if done:
            if reward==1:
                print('after {0:} steps, success at {1:}'.format(step,next_state))
            else:
                print('after {0:} steps, failed at {1:}'.format(step,next_state))
            break
        if render:
            env.render()
        state=next_state
    env.close()

after 47 steps, success at 15
after 10 steps, success at 15
after 31 steps, success at 15
after 55 steps, success at 15
after 8 steps, success at 15
after 47 steps, success at 15
after 24 steps, success at 15
after 36 steps, success at 15
after 69 steps, success at 15
after 100 steps, failed at 4
